[workspace]
members = [
    "builder",
    "driver"
]

[workspace.dependencies]
pipeline = { path = "../" }
cfg-if = "1.0"
bincode = "1.3.3"
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
